site_name: OIG Portal Docs
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
plugins:
  - search
nav:
  - Home: index.md
  - Latest Results: latestresults.md
  - Scores: score.md
  - Admin: admin.md
  - Guilds: guild.md

